const letters = {
    A: [
        "     ",
        " OOO ",
        "O   O",
        "O   O",
        "OOOOO",
        "O   O",
        "O   O",
        "O   O",
        "     ",
    ],
    B: [
        "     ",
        "OOOO ",
        "O   O",
        "O   O",
        "OOOO ",
        "O   O",
        "O   O",
        "OOOO ",
        "     ",
    ],
    C: [
        "     ",
        " OOO ",
        "O   O",
        "O    ",
        "O    ",
        "O    ",
        "O   O",
        " OOO ",
        "     ",
    ],
    D: [
        "     ",
        "OOOO ",
        "O   O",
        "O   O",
        "O   O",
        "O   O",
        "O   O",
        "OOOO ",
        "     ",
    ],
    E: [
        "     ",
        "OOOOO",
        "O    ",
        "O    ",
        "OOOO ",
        "O    ",
        "O    ",
        "OOOOO",
        "     ",
    ],
    F: [
        "     ",
        "OOOOO",
        "O    ",
        "O    ",
        "OOOO ",
        "O    ",
        "O    ",
        "O    ",
        "     ",
    ],
    G: [
        "     ",
        " OOO ",
        "O   O",
        "O    ",
        "O    ",
        "O  OO",
        "O   O",
        " OOO ",
        "     ",
    ],
    H: [
        "     ",
        "O   O",
        "O   O",
        "O   O",
        "OOOOO",
        "O   O",
        "O   O",
        "O   O",
        "     ",
    ],
    I: [
        "     ",
        " OOO ",
        "  O  ",
        "  O  ",
        "  O  ",
        "  O  ",
        "  O  ",
        " OOO ",
        "     ",
    ],
    J: [
        "     ",
        "  OOO",
        "   O ",
        "   O ",
        "   O ",
        "   O ",
        "O  O ",
        " OO  ",
        "     ",
    ],
    K: [
        "     ",
        "O   O",
        "O  O ",
        "O O  ",
        "OO   ",
        "O O  ",
        "O  O ",
        "O   O",
        "     ",
    ],
    L: [
        "     ",
        "O    ",
        "O    ",
        "O    ",
        "O    ",
        "O    ",
        "O    ",
        "OOOOO",
        "     ",
    ],
    M: [
        "     ",
        "O   O",
        "OO OO",
        "O O O",
        "O O O",
        "O   O",
        "O   O",
        "O   O",
        "     ",
    ],
    N: [
        "     ",
        "O   O",
        "O   O",
        "OO  O",
        "O O O",
        "O  OO",
        "O   O",
        "O   O",
        "     ",
    ],
    O: [
        "     ",
        " OOO ",
        "O   O",
        "O   O",
        "O   O",
        "O   O",
        "O   O",
        " OOO ",
        "     ",
    ],
    P: [
        "     ",
        "OOOO ",
        "O   O",
        "O   O",
        "OOOO ",
        "O    ",
        "O    ",
        "O    ",
        "     ",
    ],
    Q: [
        "     ",
        " OOO ",
        "O   O",
        "O   O",
        "O   O",
        "O O O",
        "O  O ",
        " OO O",
        "     ",
    ],
    R: [
        "OOOO ",
        "O   O",
        "O   O",
        "OOOO ",
        "O O  ",
        "O  O ",
        "O   O"
    ],
    S: [
        "     ",
        " OOOO",
        "O    ",
        "O    ",
        " OOO ",
        "    O",
        "    O",
        "OOOO ",
        "     ",
    ],
    T: [
        "     ",
        "OOOOO",
        "  O  ",
        "  O  ",
        "  O  ",
        "  O  ",
        "  O  ",
        "  O  ",
        "     ",
    ],
    U: [
        "     ",
        "O   O",
        "O   O",
        "O   O",
        "O   O",
        "O   O",
        "O   O",
        " OOO ",
        "     ",
    ],
    V: [
        "     ",
        "O   O",
        "O   O",
        "O   O",
        "O   O",
        " O O ",
        " O O ",
        "  O  ",
        "     ",
    ],
    W: [
        "     ",
        "O   O",
        "O   O",
        "O   O",
        "O O O",
        "O O O",
        "O O O",
        " O O ",
        "     ",
    ],
    X: [
        "     ",
        "O   O",
        "O   O",
        " O O ",
        "  O  ",
        " O O ",
        "O   O",
        "O   O",
        "     ",
    ],
    Y: [
        "     ",
        "O   O",
        "O   O",
        " O O ",
        "  O  ",
        "  O  ",
        "  O  ",
        "  O  ",
        "     ",
    ],
    Z: [
        "     ",
        "OOOOO",
        "    O",
        "   O ",
        "  O  ",
        " O   ",
        "O    ",
        "OOOOO",
        "     ",
    ],
    a: [
        "     ",
        "     ",
        " OOO ",
        "    O",
        " OOOO",
        "O   O",
        "O   O",
        " OOOO",
        "     ",
    ],
    b: [
        "     ",
        "O    ",
        "O    ",
        "O    ",
        "OOOO ",
        "O   O",
        "O   O",
        "OOOO ",
        "     ",
    ],
    c: [
        "     ",
        "     ",
        " OOO ",
        "O   O",
        "O    ",
        "O    ",
        "O   O",
        " OOO ",
        "     ",
    ],
    d: [
        "     ",
        "    O",
        "    O",
        "    O",
        " OOOO",
        "O   O",
        "O   O",
        " OOOO",
        "     ",
    ],
    e: [
        "     ",
        "     ",
        " OOO ",
        "O   O",
        "OOOOO",
        "O    ",
        "O   O",
        " OOO ",
        "     ",
    ],
    f: [
        "     ",
        "   OO",
        "  O  ",
        "  O  ",
        "OOOOO",
        "  O  ",
        "  O  ",
        "  O  ",
        "     ",
    ],
    g: [
        "     ",
        "     ",
        " OOOO",
        "O   O",
        "O   O",
        " OOOO",
        "    O",
        " OOO ",
        "     ",
    ],
    h: [
        "     ",
        "O    ",
        "O    ",
        "O    ",
        "OOOO ",
        "O   O",
        "O   O",
        "O   O",
        "     ",
    ],
    i: [
        "   ",
        " O ",
        "   ",
        " O ",
        " O ",
        " O ",
        " O ",
        " O ",
        "   ",
    ],
    j: [
        "     ",
        "   O ",
        "     ",
        "  OO ",
        "   O ",
        "   O ",
        "O  O ",
        " OO  ",
        "     ",
    ],
    k: [
        "     ",
        "O    ",
        "O    ",
        "O  O ",
        "O O  ",
        "OO   ",
        "O O  ",
        "O  O ",
        "     ",
    ],
    l: [
        "     ",
        " O ",
        " O ",
        " O ",
        " O ",
        " O ",
        " O ",
        " O ",
        "     ",
    ],
    m: [
        "     ",
        "     ",
        "OOOO ",
        "O O O",
        "O O O",
        "O O O",
        "O O O",
        "O O O",
        "     ",
    ],
    n: [
        "     ",
        "     ",
        "OOOO ",
        "O   O",
        "O   O",
        "O   O",
        "O   O",
        "O   O",
        "     ",
    ],
    o: [
        "     ",
        "     ",
        " OOO ",
        "O   O",
        "O   O",
        "O   O",
        "O   O",
        " OOO ",
        "     ",
    ],
    p: [
        "     ",
        "     ",
        "OOOO ",
        "O   O",
        "O   O",
        "OOOO ",
        "O    ",
        "O    ",
        "     ",
    ],
    q: [
        "     ",
        "     ",
        " OOOO",
        "O   O",
        "O   O",
        " OOOO",
        "    O",
        "    O",
        "     ",
    ],
    r: [
        "     ",
        "     ",
        "O OO ",
        "OO  O",
        "O    ",
        "O    ",
        "O    ",
        "O    ",
        "     ",
    ],
    s: [
        "     ",
        "     ",
        " OOO ",
        "O   O",
        " OO  ",
        "   O ",
        "O   O",
        " OOO ",
        "     ",
    ],
    t: [
        "     ",
        " O   ",
        " O   ",
        "OOOOO",
        " O   ",
        " O   ",
        " O  O",
        "  OO ",
        "     ",
    ],
    u: [
        "     ",
        "     ",
        "O   O",
        "O   O",
        "O   O",
        "O   O",
        "O   O",
        " OOO ",
        "     ",
    ],
    v: [
        "     ",
        "     ",
        "O   O",
        "O   O",
        "O   O",
        "O   O",
        " O O ",
        "  O  ",
        "     ",
    ],
    w: [
        "     ",
        "     ",
        "O   O",
        "O   O",
        "O   O",
        "O O O",
        "OO OO",
        "O   O",
        "     ",
    ],
    x: [
        "     ",
        "     ",
        "O   O",
        " O O ",
        "  O  ",
        " O O ",
        "O   O",
        "O   O",
        "     ",
    ],
    y: [
        "     ",
        "     ",
        "O   O",
        "O   O",
        "O   O",
        " OOO ",
        "   O ",
        " OO  ",
        "     ",
    ],
    z: [
        "     ",
        "     ",
        " OOOO",
        "    O",
        "   O ",
        "  O  ",
        " O   ",
        " OOOO",
        "     ",
    ],
    SPACE: [
        "    ",
        "    ",
        "    ",
        "    ",
        "    ",
        "    ",
        "    ",
        "    ",
        "    ",
    ]
};

module.exports = {
    letters: letters
};